# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rithvik/dev/metrobot/pathfinder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rithvik/dev/metrobot/pathfinder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rithvik/dev/metrobot/pathfinder/CMakeFiles /Users/rithvik/dev/metrobot/pathfinder/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rithvik/dev/metrobot/pathfinder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pathfinder

# Build rule for target.
pathfinder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pathfinder
.PHONY : pathfinder

# fast build rule for target.
pathfinder/fast:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/build
.PHONY : pathfinder/fast

#=============================================================================
# Target rules for targets named lint

# Build rule for target.
lint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint
.PHONY : lint

# fast build rule for target.
lint/fast:
	$(MAKE) -f CMakeFiles/lint.dir/build.make CMakeFiles/lint.dir/build
.PHONY : lint/fast

src/path.o: src/path.cpp.o

.PHONY : src/path.o

# target to build an object file
src/path.cpp.o:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/path.cpp.o
.PHONY : src/path.cpp.o

src/path.i: src/path.cpp.i

.PHONY : src/path.i

# target to preprocess a source file
src/path.cpp.i:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/path.cpp.i
.PHONY : src/path.cpp.i

src/path.s: src/path.cpp.s

.PHONY : src/path.s

# target to generate assembly for a file
src/path.cpp.s:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/path.cpp.s
.PHONY : src/path.cpp.s

src/pathfinder.o: src/pathfinder.cpp.o

.PHONY : src/pathfinder.o

# target to build an object file
src/pathfinder.cpp.o:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/pathfinder.cpp.o
.PHONY : src/pathfinder.cpp.o

src/pathfinder.i: src/pathfinder.cpp.i

.PHONY : src/pathfinder.i

# target to preprocess a source file
src/pathfinder.cpp.i:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/pathfinder.cpp.i
.PHONY : src/pathfinder.cpp.i

src/pathfinder.s: src/pathfinder.cpp.s

.PHONY : src/pathfinder.s

# target to generate assembly for a file
src/pathfinder.cpp.s:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/pathfinder.cpp.s
.PHONY : src/pathfinder.cpp.s

src/simulate.o: src/simulate.cpp.o

.PHONY : src/simulate.o

# target to build an object file
src/simulate.cpp.o:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/simulate.cpp.o
.PHONY : src/simulate.cpp.o

src/simulate.i: src/simulate.cpp.i

.PHONY : src/simulate.i

# target to preprocess a source file
src/simulate.cpp.i:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/simulate.cpp.i
.PHONY : src/simulate.cpp.i

src/simulate.s: src/simulate.cpp.s

.PHONY : src/simulate.s

# target to generate assembly for a file
src/simulate.cpp.s:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/simulate.cpp.s
.PHONY : src/simulate.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/vec.o: src/vec.cpp.o

.PHONY : src/vec.o

# target to build an object file
src/vec.cpp.o:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/vec.cpp.o
.PHONY : src/vec.cpp.o

src/vec.i: src/vec.cpp.i

.PHONY : src/vec.i

# target to preprocess a source file
src/vec.cpp.i:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/vec.cpp.i
.PHONY : src/vec.cpp.i

src/vec.s: src/vec.cpp.s

.PHONY : src/vec.s

# target to generate assembly for a file
src/vec.cpp.s:
	$(MAKE) -f CMakeFiles/pathfinder.dir/build.make CMakeFiles/pathfinder.dir/src/vec.cpp.s
.PHONY : src/vec.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pathfinder"
	@echo "... lint"
	@echo "... src/path.o"
	@echo "... src/path.i"
	@echo "... src/path.s"
	@echo "... src/pathfinder.o"
	@echo "... src/pathfinder.i"
	@echo "... src/pathfinder.s"
	@echo "... src/simulate.o"
	@echo "... src/simulate.i"
	@echo "... src/simulate.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/vec.o"
	@echo "... src/vec.i"
	@echo "... src/vec.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

